### ISSUE TITLE
Massive GPU memory usage during evaluation

### ISSUE THREAD

**Issue by vinson2233** [mlfoundations/open_clip#11]
# Machine setup
```
Google cloud VM
Debian10
16 cores CPU, 60Gb of rams
4 nvidia T4
```

# Error
```
Traceback (most recent call last):
  File "/opt/conda/envs/open_clip/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/jupyter/open_clip/src/training/main.py", line 192, in main_worker
    evaluate(model, data, 0, args, writer, 0)
  File "/home/jupyter/open_clip/src/training/train.py", line 197, in evaluate
    torch.cat(all_image_features), torch.cat(all_text_features)
  File "/home/jupyter/open_clip/src/training/train.py", line 228, in get_metrics
    logits_per_image = image_features @ text_features.t()
RuntimeError: CUDA out of memory. Tried to allocate 2269.88 GiB (GPU 0; 14.76 GiB total capacity; 7.11 GiB already allocated; 6.67 GiB free; 7.17 GiB reserved in total by PyTorch)
```

# The script I use :
```
python -u src/training/main.py \
    --save-frequency 1 \
    --zeroshot-frequency 3 \
    --train-data "src/df_openclip_train.csv"  \
    --val-data "src/df_openclip_val.csv"  \
    --openai-pretrained \
    --csv-separator "," \
    --csv-img-key image_path \
    --csv-caption-key product_name \
    --warmup 10000 \
    --batch-size=128 \
    --lr=1e-3 \
    --wd=0.1 \
    --epochs=30 \
    --workers=4 \
    --model ViT-B/32
```

# Full setting
```
2021-09-01,05:15:43 | INFO | Rank 0 | Params:
2021-09-01,05:15:43 | INFO | Rank 0 |   C: 3.16
2021-09-01,05:15:43 | INFO | Rank 0 |   aggregate: True
2021-09-01,05:15:43 | INFO | Rank 0 |   batch_size: 128
2021-09-01,05:15:43 | INFO | Rank 0 |   beta1: 0.9
2021-09-01,05:15:43 | INFO | Rank 0 |   beta2: 0.98
2021-09-01,05:15:43 | INFO | Rank 0 |   checkpoint_path: ./logs/lr=0.001_wd=0.1_agg=True_model=ViT-B/32_batchsize=128_workers=4_date=2021-09-01-05-15-41/checkpoints
2021-09-01,05:15:43 | INFO | Rank 0 |   copy_codebase: False
2021-09-01,05:15:43 | INFO | Rank 0 |   csv_caption_key: product_name
2021-09-01,05:15:43 | INFO | Rank 0 |   csv_img_key: image_path
2021-09-01,05:15:43 | INFO | Rank 0 |   csv_separator: ,
2021-09-01,05:15:43 | INFO | Rank 0 |   dataset_type: auto
2021-09-01,05:15:43 | INFO | Rank 0 |   debug: False
2021-09-01,05:15:43 | INFO | Rank 0 |   dist_backend: nccl
2021-09-01,05:15:43 | INFO | Rank 0 |   dist_url: tcp://127.0.0.1:6100
2021-09-01,05:15:43 | INFO | Rank 0 |   distributed: True
2021-09-01,05:15:43 | INFO | Rank 0 |   dp: False
2021-09-01,05:15:43 | INFO | Rank 0 |   epochs: 30
2021-09-01,05:15:43 | INFO | Rank 0 |   eps: 1e-06
2021-09-01,05:15:43 | INFO | Rank 0 |   gpu: 0
2021-09-01,05:15:43 | INFO | Rank 0 |   imagenet_v2: None
2021-09-01,05:15:43 | INFO | Rank 0 |   imagenet_val: None
2021-09-01,05:15:43 | INFO | Rank 0 |   log_level: 20
2021-09-01,05:15:43 | INFO | Rank 0 |   log_path: ./logs/lr=0.001_wd=0.1_agg=True_model=ViT-B/32_batchsize=128_workers=4_date=2021-09-01-05-15-41/out.log
2021-09-01,05:15:43 | INFO | Rank 0 |   logs: ./logs/
2021-09-01,05:15:43 | INFO | Rank 0 |   lr: 0.001
2021-09-01,05:15:43 | INFO | Rank 0 |   model: ViT-B/32
2021-09-01,05:15:43 | INFO | Rank 0 |   multigpu: None
2021-09-01,05:15:43 | INFO | Rank 0 |   name: lr=0.001_wd=0.1_agg=True_model=ViT-B/32_batchsize=128_workers=4_date=2021-09-01-05-15-41
2021-09-01,05:15:43 | INFO | Rank 0 |   ngpus_per_node: 4
2021-09-01,05:15:43 | INFO | Rank 0 |   openai_pretrained: True
2021-09-01,05:15:43 | INFO | Rank 0 |   precision: amp
2021-09-01,05:15:43 | INFO | Rank 0 |   rank: 0
2021-09-01,05:15:43 | INFO | Rank 0 |   regression_frequency: 2
2021-09-01,05:15:43 | INFO | Rank 0 |   report_to: 
2021-09-01,05:15:43 | INFO | Rank 0 |   resume: None
2021-09-01,05:15:43 | INFO | Rank 0 |   save_frequency: 1
2021-09-01,05:15:43 | INFO | Rank 0 |   skip_aggregate: False
2021-09-01,05:15:43 | INFO | Rank 0 |   skip_scheduler: False
2021-09-01,05:15:43 | INFO | Rank 0 |   tensorboard: False
2021-09-01,05:15:43 | INFO | Rank 0 |   tensorboard_path: 
2021-09-01,05:15:43 | INFO | Rank 0 |   train_data: src/df_openclip_train.csv
2021-09-01,05:15:43 | INFO | Rank 0 |   use_bn_sync: False
2021-09-01,05:15:43 | INFO | Rank 0 |   val_data: src/df_openclip_val.csv
2021-09-01,05:15:43 | INFO | Rank 0 |   wandb: False
2021-09-01,05:15:43 | INFO | Rank 0 |   wandb_notes: 
2021-09-01,05:15:43 | INFO | Rank 0 |   warmup: 10000
2021-09-01,05:15:43 | INFO | Rank 0 |   wd: 0.1
2021-09-01,05:15:43 | INFO | Rank 0 |   workers: 4
2021-09-01,05:15:43 | INFO | Rank 0 |   world_size: 4
2021-09-01,05:15:43 | INFO | Rank 0 |   zeroshot_frequency: 3
2021-09-01,05:15:47 | INFO | Rank 0 | Use GPU: 0 for training
2021-09-01,05:15:47 | INFO | Rank 1 | Use GPU: 1 for training
2021-09-01,05:15:47 | INFO | Rank 2 | Use GPU: 2 for training
2021-09-01,05:15:47 | INFO | Rank 3 | Use GPU: 3 for training
```

# Info about the data : 
Training data consist of 2.9 million pairs of text-image
Validation data consist of 780k pairs of text-image

# Potential cause of the error
The `get_metrics` function is call on whole evaluation data embedding at once, which is massive. In my cases, the matrix multiplication involving 2 matrix with size of 780k x 512 which requires 2000 Gb of GPU memory

**Comment by gabrielilharco** [comment]
Hi @vinson2233, thanks for the details!

During evaluation, we compute metrics such as recall @ k. As you pointed out, this involves some very big matrices if the evaluation dataset is big (in your case, a matrix of size 780k x 780k). 

I think there are two scenarios here:

**Scenario 1)** You are indeed interested in knowing these metrics on a large validation set

If it's infeasible to compute the big matrix, one slower (but less memory intensive) alternative would be to transform this into a loop. More concretely, you can loop over every caption; for each caption, you compute the similarity with all images, and find the rank of the correctly paired image. Same for every image.

Alternatively, one faster but inexact solution is to use a nearest neighbor search tool, such as FAISS (https://github.com/facebookresearch/faiss) 

**Scenario 2)** You just want a good model

If you care less about the specific value of these metrics on your large validation set, I'd recommend either (i) using a smaller validation set (truncating the csv file will do); or (2) simply looking at zero-shot metrics

Does this help?

**Comment by vinson2233** [comment]
@gabrielilharco Sure, it really help.

Right now I'm truncating my validation data to just 10k pairs. I don't know much about faiss right now, maybe I will try to use that for evaluating. Thank you :)
