### ISSUE TITLE
KeyError: 'filepath'

### ISSUE THREAD

**Issue by snow1929** [mlfoundations/open_clip#144]
when I run the code for training, there is an error happend
But I have no idea, what's wrong with it.
Do you face the error before?

```
2022-08-02,16:02:09 | INFO | Params:
2022-08-02,16:02:09 | INFO |   batch_size: 128
2022-08-02,16:02:09 | INFO |   beta1: 0.9
2022-08-02,16:02:09 | INFO |   beta2: 0.98
2022-08-02,16:02:09 | INFO |   checkpoint_path: ./logs/2022_08_02-16_01_50-model_ViT-B-32-lr_0.001-b_128-j_8-p_amp\checkpoints
2022-08-02,16:02:09 | INFO |   copy_codebase: False
2022-08-02,16:02:09 | INFO |   csv_caption_key: title
2022-08-02,16:02:09 | INFO |   csv_img_key: filepath
2022-08-02,16:02:09 | INFO |   csv_separator:
2022-08-02,16:02:09 | INFO |   dataset_resampled: False
2022-08-02,16:02:09 | INFO |   dataset_type: auto
2022-08-02,16:02:09 | INFO |   ddp_static_graph: False
2022-08-02,16:02:09 | INFO |   debug: False
2022-08-02,16:02:09 | INFO |   device: cuda:0
2022-08-02,16:02:09 | INFO |   dist_backend: nccl
2022-08-02,16:02:09 | INFO |   dist_url: env://
2022-08-02,16:02:09 | INFO |   distributed: False
2022-08-02,16:02:09 | INFO |   epochs: 30
2022-08-02,16:02:09 | INFO |   eps: 1e-06
2022-08-02,16:02:09 | INFO |   force_quick_gelu: False
2022-08-02,16:02:09 | INFO |   gather_with_grad: False
2022-08-02,16:02:09 | INFO |   grad_checkpointing: False
2022-08-02,16:02:09 | INFO |   horovod: False
2022-08-02,16:02:09 | INFO |   imagenet_v2: None
2022-08-02,16:02:09 | INFO |   imagenet_val: None
2022-08-02,16:02:09 | INFO |   local_loss: False
2022-08-02,16:02:09 | INFO |   local_rank: 0
2022-08-02,16:02:09 | INFO |   lock_image: False
2022-08-02,16:02:09 | INFO |   lock_image_freeze_bn_stats: False
2022-08-02,16:02:09 | INFO |   lock_image_unlocked_groups: 0
2022-08-02,16:02:09 | INFO |   log_level: 20
2022-08-02,16:02:09 | INFO |   log_local: False
2022-08-02,16:02:09 | INFO |   log_path: ./logs/2022_08_02-16_01_50-model_ViT-B-32-lr_0.001-b_128-j_8-p_amp\out.log
2022-08-02,16:02:09 | INFO |   logs: ./logs/
2022-08-02,16:02:09 | INFO |   lr: 0.001
2022-08-02,16:02:09 | INFO |   model: ViT-B-32
2022-08-02,16:02:09 | INFO |   name: 2022_08_02-16_01_50-model_ViT-B-32-lr_0.001-b_128-j_8-p_amp
2022-08-02,16:02:09 | INFO |   no_set_device_rank: False
2022-08-02,16:02:09 | INFO |   precision: amp
2022-08-02,16:02:09 | INFO |   pretrained:
2022-08-02,16:02:09 | INFO |   pretrained_image: False
2022-08-02,16:02:09 | INFO |   rank: 0
2022-08-02,16:02:09 | INFO |   report_to: tensorboard
2022-08-02,16:02:09 | INFO |   resume: None
2022-08-02,16:02:09 | INFO |   save_frequency: 1
2022-08-02,16:02:09 | INFO |   save_most_recent: False
2022-08-02,16:02:09 | INFO |   seed: 0
2022-08-02,16:02:09 | INFO |   skip_scheduler: False
2022-08-02,16:02:09 | INFO |   tensorboard: True
2022-08-02,16:02:09 | INFO |   tensorboard_path: ./logs/2022_08_02-16_01_50-model_ViT-B-32-lr_0.001-b_128-j_8-p_amp\tensorboard
2022-08-02,16:02:09 | INFO |   torchscript: False
2022-08-02,16:02:09 | INFO |   trace: False
2022-08-02,16:02:09 | INFO |   train_data: D:\ai\open_clip-main\image\label_training.csv
2022-08-02,16:02:09 | INFO |   train_num_samples: None
2022-08-02,16:02:09 | INFO |   use_bn_sync: False
2022-08-02,16:02:09 | INFO |   val_data: D:\ai\open_clip-main\image\label_test.csv
2022-08-02,16:02:09 | INFO |   val_frequency: 1
2022-08-02,16:02:09 | INFO |   val_num_samples: None
2022-08-02,16:02:09 | INFO |   wandb: False
2022-08-02,16:02:09 | INFO |   wandb_notes:
2022-08-02,16:02:09 | INFO |   warmup: 10000
2022-08-02,16:02:09 | INFO |   wd: 0.1
2022-08-02,16:02:09 | INFO |   workers: 8
2022-08-02,16:02:09 | INFO |   world_size: 1
2022-08-02,16:02:09 | INFO |   zeroshot_frequency: 1
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'filepath'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\ai\open_clip-main\src\training\main.py", line 307, in <module>
    main()
  File "D:\ai\open_clip-main\src\training\main.py", line 213, in main
    data = get_data(args, (preprocess_train, preprocess_val), epoch=start_epoch)
  File "D:\ai\open_clip-main\src\training\data.py", line 445, in get_data
    data["train"] = get_dataset_fn(args.train_data, args.dataset_type)(
  File "D:\ai\open_clip-main\src\training\data.py", line 397, in get_csv_dataset
    dataset = CsvDataset(
  File "D:\ai\open_clip-main\src\training\data.py", line 37, in __init__
    self.images = df[img_key].tolist()
  File "C:\Users\user\anaconda3\lib\site-packages\pandas\core\frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Users\user\anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'filepath'
```

**Comment by rom1504** [comment]
It seems to fail reading your CSV file. Try to run the pandas line that
read it alone

**Comment by snow1929** [comment]
If I use my dataset.
how to impirt data?
edit the csv file to record the image path(full path) and label
![image](https://user-images.githubusercontent.com/42559501/182498250-9aa7a928-929c-4e92-a2ac-21321c89fc72.png)

Is that right
```
python -m training.main  --save-frequency 1  --zeroshot-frequency 1 --report-to tensorboard --train-data="E:\\AI\open_clip-main\image\label_training.csv"  --val-data="E:\\AI\open_clip-main\image\label_test.csv"  --batch-size=128 --lr=1e-3 --wd=0.1 --epochs=30 --workers=8 --model ViT-B/32
```

**Comment by rom1504** [comment]
Try to run the pandas line that read it alone

**Comment by John-Kieron** [comment]
Do I need to transform the tar format of dataset to csv format? I download the dataset using img2dataset, and its result is tar files containing jpg, json and text with captions.

**Comment by gabrielilharco** [comment]
There is no need to transform to csv, this codebase accepts tar files as inputs. See https://github.com/mlfoundations/open_clip/issues/148#issuecomment-1463335568, and let me know if you have any questions.

**Comment by starandharry** [comment]
I got the same error: KeyError: 'filepath'
what is called "Try to run the pandas line that read it alone?" Could you please provide more details?
@rom1504

**Comment by phongDepTrai** [comment]
I think the issue is that the csv_separator you used is ","
Replacing the separator with "\t" may work.

**Comment by ShuxunoO** [comment]
the another way to handle the problem is to set the 

**`--csv-separator="," \`**

the same issue troubles me a long time,
hopes this can help you

**Comment by goodrain553** [comment]
> the another way to handle the problem is to set the
> 
> **`--csv-separator="," \`**
> 
> the same issue troubles me a long time, hopes this can help you

definitely you are right, lots of csv files are separated with ","
