### ISSUE TITLE
Bug: Bad Request with ViT H 14 laion2b_s32b_b79k

### ISSUE THREAD

**Issue by TheImunityGamer** [mlfoundations/open_clip#348]
I was trying to use SD 2.0 and 2.1. I kept getting the same error. I narrowed it down to the use of open_clip. I'm using open-clip-torch 2.7.0. I then tried to use open_clip.create_model_and_transforms in the python console. The exact function I used was `model, _, _ = open_clip.create_model_and_transforms("ViT-H-14", device=device('cuda'), pretrained="laion2b_s32b_b79k")`. This didn't work in 2.7.0 or 2.9.3 with Python 3.10.7. I also uninstalled and reinstalled Python. It should be possible since it was used here: #168.

Here is the full error:
model, _, _ = open_clip.create_model_and_transforms("ViT-H-14", device=device('cuda'), pretrained="laion2b_s32b_b79k")
Traceback (most recent call last):
  File "D:\Stable Diffusion\SD 2\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_errors.py", line 239, in hf_raise_for_status
    response.raise_for_status()
  File "D:\Stable Diffusion\SD 2\stable-diffusion-webui\venv\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://huggingface.co/laion/CLIP-ViT-H-14-laion2B-s32B-b79K/resolve/main/open_clip_pytorch_model.bin

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Stable Diffusion\SD 2\stable-diffusion-webui\venv\lib\site-packages\open_clip\factory.py", line 207, in create_model_and_transforms
    model = create_model(
  File "D:\Stable Diffusion\SD 2\stable-diffusion-webui\venv\lib\site-packages\open_clip\factory.py", line 164, in create_model
    checkpoint_path = download_pretrained(pretrained_cfg, cache_dir=cache_dir)
  File "D:\Stable Diffusion\SD 2\stable-diffusion-webui\venv\lib\site-packages\open_clip\pretrained.py", line 312, in download_pretrained
    target = download_pretrained_from_hf(model_id, cache_dir=cache_dir)
  File "D:\Stable Diffusion\SD 2\stable-diffusion-webui\venv\lib\site-packages\open_clip\pretrained.py", line 282, in download_pretrained_from_hf
    cached_file = hf_hub_download(model_id, filename, revision=revision, cache_dir=cache_dir)
  File "D:\Stable Diffusion\SD 2\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\Stable Diffusion\SD 2\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 1067, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "D:\Stable Diffusion\SD 2\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\Stable Diffusion\SD 2\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\file_download.py", line 1376, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "D:\Stable Diffusion\SD 2\stable-diffusion-webui\venv\lib\site-packages\huggingface_hub\utils\_errors.py", line 276, in hf_raise_for_status
    raise BadRequestError(message, response=response) from e
huggingface_hub.utils._errors.BadRequestError:

Bad request:

**Comment by rwightman** [comment]
@TheImunityGamer it seems like a weight download issue, could be transient? or could be an old version of huggingface_hub? have you tried updating to latest hub version?

**Comment by TheImunityGamer** [comment]
Ok, after a bit of messing around, I got it working using huggingface-hub 0.9.1. I was using the most recent version of huggingface-hub, 0.11.1, but it didn't work, nor did version 0.10.1. Everything seems to be working perfectly with 0.9.1. Thanks.

**Comment by rwightman** [comment]
@TheImunityGamer thanks for the update, unexpected that newer hub ver were having issues, I'll take a look at that
