### ISSUE TITLE
Unknown model (convnext_xxlarge)

### ISSUE THREAD

**Issue by orrzohar** [mlfoundations/open_clip#477]
It seems like convnext_xxlarge is not recognized for some reason: 

>>> tmp = open_clip.list_pretrained()[-5]

>>> tmp
('convnext_xxlarge', 'laion2b_s34b_b82k_augreg_soup')

>>> open_clip.create_model_and_transforms(tmp[0], pretrained=tmp[1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/orrzohar/anaconda3/envs/LOVM/lib/python3.10/site-packages/open_clip/factory.py", line 292, in create_model_and_transforms
    model = create_model(
  File "/home/orrzohar/anaconda3/envs/LOVM/lib/python3.10/site-packages/open_clip/factory.py", line 194, in create_model
    model = CLIP(**model_cfg, cast_dtype=cast_dtype)
  File "/home/orrzohar/anaconda3/envs/LOVM/lib/python3.10/site-packages/open_clip/model.py", line 190, in __init__
    self.visual = _build_vision_tower(embed_dim, vision_cfg, quick_gelu, cast_dtype)
  File "/home/orrzohar/anaconda3/envs/LOVM/lib/python3.10/site-packages/open_clip/model.py", line 90, in _build_vision_tower
    visual = TimmModel(
  File "/home/orrzohar/anaconda3/envs/LOVM/lib/python3.10/site-packages/open_clip/timm_model.py", line 53, in __init__
    self.trunk = timm.create_model(model_name, pretrained=pretrained, **timm_kwargs)
  File "/home/orrzohar/anaconda3/envs/LOVM/lib/python3.10/site-packages/timm/models/factory.py", line 67, in create_model
    raise RuntimeError('Unknown model (%s)' % model_name)
RuntimeError: Unknown model (convnext_xxlarge)

**Comment by rwightman** [comment]
@orrzohar timm still needs to be a 0.8.x pre-release (`pip install --pre timm`) for that model but didn't want to make it a hard dep as not everyone cares about those
