### ISSUE TITLE
Dataloader stuck

### ISSUE THREAD

**Issue by samuelstevens** [mlfoundations/open_clip#480]
Hi, I'm trying to train a pretrained CLIP on a subset of iNat21 (8K classes, ~2.1M images). I created a sharded webdataset with 324 1GB shards (2,149,509 examples). I'm using single-node multi-gpu training:

```sh
torchrun --nproc_per_node 4 -m training.main \
  --dataset-type webdataset \
  --train-data '/local/scratch/cv_datasets/inat21/rand-species-split/pretrain-webdataset/train/shards/shard-{000000..000324}.tar' \
  --train-num-samples 2149509 \
  --val-data '/local/scratch/cv_datasets/inat21/rand-species-split/pretrain-webdataset/val/shards/shard-{000000..000013}.tar' \                                                               
  --val-num-samples 80000 \
  --dataset-resampled \
  --workers 4 \
  --precision amp \
  --warmup 2000 \
  --epochs 32 \                                                                                                                                                                               
  --batch-size 256 \                                                                                                                                                                          
  --log-every-n-steps 1 \
  --local-loss \
  --gather-with-grad \
  --save-frequency 1 \
  --model RN50 \
  --pretrained openai \
  --image-mean 0.4632 0.4800 0.3762 \
  --image-std 0.2375 0.2291 0.2474 \
  --report-to wandb \
  --wandb-project-name open_clip \
  --seed 42
```

I get to `2023-04-04,00:16:35 | INFO | Start epoch 0` but then no progress from here. When I cancel (typically after 10-15 minutes), this is my stack trace:

```
Traceback (most recent call last):
  File "/home/stevens.994/projects/open_clip/.venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/home/stevens.994/projects/open_clip/.venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1329, in _next_data
    idx, data = self._get_data()
  File "/home/stevens.994/projects/open_clip/.venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1295, in _get_data
    success, data = self._try_get_data()
  File "/home/stevens.994/projects/open_clip/.venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1133, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/stevens.994/.pyenv/versions/3.10.9/lib/python3.10/multiprocessing/queues.py", line 113, in get
    if not self._poll(timeout):
  File "/home/stevens.994/.pyenv/versions/3.10.9/lib/python3.10/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/stevens.994/.pyenv/versions/3.10.9/lib/python3.10/multiprocessing/connection.py", line 424, in _poll
    r = wait([self], timeout)
  File "/home/stevens.994/.pyenv/versions/3.10.9/lib/python3.10/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/home/stevens.994/.pyenv/versions/3.10.9/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stevens.994/.pyenv/versions/3.10.9/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/stevens.994/.pyenv/versions/3.10.9/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/stevens.994/projects/open_clip/src/training/main.py", line 470, in <module>
    main(sys.argv[1:])
  File "/home/stevens.994/projects/open_clip/src/training/main.py", line 398, in main
    train_one_epoch(model, data, loss, epoch, optimizer, scaler, scheduler, dist_model, args, tb_writer=writer)
  File "/home/stevens.994/projects/open_clip/src/training/train.py", line 84, in train_one_epoch
    for i, batch in enumerate(dataloader):
  File "/home/stevens.994/projects/open_clip/.venv/lib/python3.10/site-packages/webdataset/pipeline.py", line 64, in iterator
    for sample in self.iterator1():
  File "/home/stevens.994/projects/open_clip/.venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    with torch.autograd.profiler.record_function(self._profile_name):
  File "/home/stevens.994/projects/open_clip/.venv/lib/python3.10/site-packages/torch/autograd/profiler.py", line 507, in __exit__
    torch.ops.profiler._record_function_exit._RecordFunction(record)
  File "/home/stevens.994/projects/open_clip/.venv/lib/python3.10/site-packages/torch/_ops.py", line 482, in __getattr__
    overload = OpOverload(self, op_, op_dk_, schema, tags)
  File "/home/stevens.994/projects/open_clip/.venv/lib/python3.10/site-packages/torch/_ops.py", line 239, in __init__
    def __init__(self, overloadpacket, op, op_dk, schema, tags):
KeyboardInterrupt
```

It's stuck in the iterating thorough the dataloader. Is this expected behavior?

**Comment by zhzxlcc** [comment]
I have the same problem as yours. Did you find the solution? looking forward~

**Comment by samuelstevens** [comment]
No, but I let it sit at this point overnight (~8 hours) and it still didn't make any progress. To me, this implies:

1. I set up my webdataset incorrectly (maybe `data.py`'s `filter_no_caption_or_no_image` is filtering everything?)
2. I set up my data options incorrectly (maybe it's infeasible to shuffle 300GB of images? But pytorch can do it just fine)
3. There is a bug (hopefully not).

**Comment by gabrielilharco** [comment]
Hi @samuelstevens , it's possible that the code is hanging because the dataloader is trying to yield valid samples but there are none. Can you give more details about what's inside your tar files?

**Comment by samuelstevens** [comment]
Here's my script: 

```py
dataset = torchvision.datasets.ImageFolder(                                                                                                                                                     
    os.path.join(inat_root, split),
    transform=torchvision.transforms.Resize(resize_size, antialias=True),
)

sink = webdataset.ShardWriter(os.path.join(output_root, shard_pattern), maxsize=max_size)

for i, (image, cls) in enumerate(tqdm(dataset)):
    label = parse(dataset.classes[cls])
    desc = " ".join(label)
    sink.write({
        "__key__": f"sample{i:08d}", 
        "input.jpg": image, 
        "outputs.txt": desc,
    })

sink.close()
```

When I `print(has_caption, has_image)`, they are both false, so I think I've set my shards up incorrectly. 

Given 

```sh
$ tar -tvf shard-000000.tar
-r--r--r-- bigdata/bigdata 62704 2023-04-04 09:19 sample00000000.input.jpg
-r--r--r-- bigdata/bigdata    73 2023-04-04 09:19 sample00000000.outputs.txt
-r--r--r-- bigdata/bigdata 57640 2023-04-04 09:19 sample00000001.input.jpg
-r--r--r-- bigdata/bigdata    73 2023-04-04 09:19 sample00000001.outputs.txt
-r--r--r-- bigdata/bigdata 45566 2023-04-04 09:19 sample00000002.input.jpg
-r--r--r-- bigdata/bigdata    73 2023-04-04 09:19 sample00000002.outputs.txt
-r--r--r-- bigdata/bigdata 53337 2023-04-04 09:19 sample00000003.input.jpg
-r--r--r-- bigdata/bigdata    73 2023-04-04 09:19 sample00000003.outputs.txt
-r--r--r-- bigdata/bigdata 27954 2023-04-04 09:19 sample00000004.input.jpg
-r--r--r-- bigdata/bigdata    73 2023-04-04 09:19 sample00000004.outputs.txt
[truncated]
```

What should the file format be inside the tar files?

**Comment by gabrielilharco** [comment]
@samuelstevens indeed it looks like your tar files are not in the expected format. Webdataset groups the samples by prefix, and it will think `sample00000000.input.jpg` and `sample00000000.outputs.txt` are not from the same sample (the corresponding prefixes being `sample00000000.input` and `sample00000000.outputs`, which are different). 

A solution is to rename your files inside your tar to something like this:

```
sample00000000.jpg
sample00000000.txt
sample00000001.jpg
sample00000001.txt
...
```
