### ISSUE TITLE
Entry Not Found Error for JSON file when using OpenCLIP ViT-H/14

### ISSUE THREAD

**Issue by jellyheadandrew** [mlfoundations/open_clip#521]
Hi, thanks for open-sourcing the OpenCLIP.

I'm trying to use your OpenCLIP ViT-H/14, but am facing problems when I follow the exact instructions provided in Huggingface repo (https://huggingface.co/laion/CLIP-ViT-H-14-frozen-xlm-roberta-large-laion5B-s13B-b90k).

Specifically, I tried:

`import open_clip

model, preprocess_train, preprocess_val = open_clip.create_model_and_transforms('hf-hub:laion/CLIP-ViT-H-14-frozen-xlm-roberta-large-laion5B-s13B-b90k')
tokenizer = open_clip.get_tokenizer('hf-hub:laion/CLIP-ViT-H-14-frozen-xlm-roberta-large-laion5B-s13B-b90k')`

However, I am facing following errors:

Traceback (most recent call last):
  File "/home/hansookwan/anaconda3/envs/multidiffusion/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 259, in hf_raise_for_status
    response.raise_for_status()
  File "/home/hansookwan/anaconda3/envs/multidiffusion/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/laion/CLIP-ViT-H-14-frozen-xlm-roberta-large-laion5B-s13B-b90k/resolve/main/open_clip_config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hansookwan/SSD/RESEARCH7_SynergizingDiffusion/exp1/test_diffusion_timestep.py", line 205, in <module>
    sd = MultiDiffusion_PLUS_GlobalSemantics(device, opt.sd_version)
  File "/home/hansookwan/SSD/RESEARCH7_SynergizingDiffusion/exp1/test_diffusion_timestep.py", line 66, in __init__
    model, preprocess_train, preprocess_val = open_clip.create_model_and_transforms('hf-hub:laion/CLIP-ViT-H-14-frozen-xlm-roberta-large-laion5B-s13B-b90k')
  File "/home/hansookwan/anaconda3/envs/multidiffusion/lib/python3.9/site-packages/open_clip/factory.py", line 292, in create_model_and_transforms
    model = create_model(
  File "/home/hansookwan/anaconda3/envs/multidiffusion/lib/python3.9/site-packages/open_clip/factory.py", line 127, in create_model
    config_path = download_pretrained_from_hf(model_id, filename='open_clip_config.json', cache_dir=cache_dir)
  File "/home/hansookwan/anaconda3/envs/multidiffusion/lib/python3.9/site-packages/open_clip/pretrained.py", line 373, in download_pretrained_from_hf
    cached_file = hf_hub_download(model_id, filename, revision=revision, cache_dir=cache_dir)
  File "/home/hansookwan/anaconda3/envs/multidiffusion/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/hansookwan/anaconda3/envs/multidiffusion/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1195, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/home/hansookwan/anaconda3/envs/multidiffusion/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/hansookwan/anaconda3/envs/multidiffusion/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1541, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/home/hansookwan/anaconda3/envs/multidiffusion/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 269, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-6457b0fc-77d41e842d04e14330e09707)

Entry Not Found for url: https://huggingface.co/laion/CLIP-ViT-H-14-frozen-xlm-roberta-large-laion5B-s13B-b90k/resolve/main/open_clip_config.json.

Seems the JSON file is not available. Any solutions?

**Comment by 27yw** [comment]
hi same error with you. any help?

**Comment by jbbqqf** [comment]
Hi! Triaging older issues — this looks like a usage question that has a one-line fix using the open_clip-registered model name rather than the `hf-hub:...` direct path.

The model you're loading is already pre-registered in open_clip under the name `xlm-roberta-large-ViT-H-14` with pretrained tag `frozen_laion5b_s13b_b90k`. Loading it that way bypasses the missing `open_clip_config.json` on the HF repo because open_clip reads the architecture from its own bundled config:

```python
import open_clip
model, preprocess_train, preprocess_val = open_clip.create_model_and_transforms(
    'xlm-roberta-large-ViT-H-14',
    pretrained='frozen_laion5b_s13b_b90k',
)
tokenizer = open_clip.get_tokenizer('xlm-roberta-large-ViT-H-14')
```

Evidence:
- [`src/open_clip/pretrained.py`](https://github.com/mlfoundations/open_clip/blob/main/src/open_clip/pretrained.py): `_xlmRobertaLargeFrozenViTH14 = dict(frozen_laion5b_s13b_b90k=_pcfg(hf_hub='laion/CLIP-ViT-H-14-frozen-xlm-roberta-large-laion5B-s13B-b90k/'))` and the registry entry `"xlm-roberta-large-ViT-H-14": _xlmRobertaLargeFrozenViTH14`.
- [`src/open_clip/model_configs/xlm-roberta-large-ViT-H-14.json`](https://github.com/mlfoundations/open_clip/blob/main/src/open_clip/model_configs/xlm-roberta-large-ViT-H-14.json) — the bundled architecture config that the `hf-hub:` direct path was trying (and failing) to download from HF.
- Querying the HF API for the model repo (`https://huggingface.co/api/models/laion/CLIP-ViT-H-14-frozen-xlm-roberta-large-laion5B-s13B-b90k`) confirms its only siblings are `README.md`, `open_clip_pytorch_model.bin`, `preprocessor_config.json`, `results_xlm_roberta_large.png`, `tokenizer.json` — no `open_clip_config.json`, which is why the `hf-hub:` autoloader 404s. The model pre-dates that scheme.

If I'm wrong about the registered name covering your use case (e.g. you actually need to load weights from a fork that doesn't match the canonical config), point me at the version/fork and I'll dig further. Otherwise would you mind closing this out?

---
*Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the registry entries, model config, and HF API response were verified manually.*
