### ISSUE TITLE
Loading OpenAI's pretrained model on the hugging face

### ISSUE THREAD

**Issue by muyuan-ma** [mlfoundations/open_clip#760]
I want to use OpenAI's pretrained model on the hugging face, which is bin file, but when I set the argument `model` as `ViT-L-14-336` and set the argument `pretrained` as the path of weight such as `/path/to/openai/pytorch_model.bin`(which I downloaded on https://huggingface.co/openai/clip-vit-large-patch14-336/tree/main), I meet the Missing key(s) in state_dict errpr.

`Traceback (most recent call last):
  File "/work/home/panjiancheng/miniconda3/envs/dtk23.04_torch1.10/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/work/home/panjiancheng/miniconda3/envs/dtk23.04_torch1.10/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/work/home/panjiancheng/open_clip_mmy/src_bak/training/sr_main.py", line 510, in <module>
    main(sys.argv[1:])
  File "/work/home/panjiancheng/open_clip_mmy/src_bak/training/sr_main.py", line 225, in main
    model, preprocess_train, preprocess_val = create_model_and_transforms(
  File "/work/home/panjiancheng/open_clip_mmy/src_bak/open_clip/factory.py", line 384, in create_model_and_transforms
    model = create_model(
  File "/work/home/panjiancheng/open_clip_mmy/src_bak/open_clip/factory.py", line 290, in create_model
    load_checkpoint(model, checkpoint_path)
  File "/work/home/panjiancheng/open_clip_mmy/src_bak/open_clip/factory.py", line 161, in load_checkpoint
    incompatible_keys = model.load_state_dict(state_dict, strict=strict)
  File "/work/home/panjiancheng/miniconda3/envs/dtk23.04_torch1.10/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CLIP:`

I want to know weather the code support OpenAI's weight on the hugging face or not.

Thank you!

**Comment by gabrielilharco** [comment]
Hi @muyuan-ma, I haven't looked into the error yet, but any reason not to use `--pretrained=openai`?

**Comment by rwightman** [comment]
@muyuan-ma those weights are transformers weights not OpenCLIP. `--pretrained=openai` loads openai checkpoints from their original location, you can also download the checkpoint manually and pass the path to the ckecpoint file in `--pretrained=/path/to/model.pt` as I fixed loading OpenAI jit'd checkpoints from files in  https://github.com/mlfoundations/open_clip/issues/622
